apps/planner_web/lib/planner_web/router.ex
defmodule PlannerWeb.Router do
  use PlannerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {PlannerWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug PlannerWeb.Plugs.Locale
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug PlannerWeb.Plugs.ApiAuthorizationPlug
  end

  pipeline :auth do
    plug PlannerWeb.Pipeline
    plug PlannerWeb.CurrentUser
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :ensure_no_auth do
    plug Guardian.Plug.EnsureNotAuthenticated
  end

  pipeline :allowed_for_users do
    plug PlannerWeb.Plugs.AuthorizationPlug, ["Admin", "User"]
  end

  pipeline :allowed_for_admins do
    plug PlannerWeb.Plugs.AuthorizationPlug, ["Admin"]
  end

  scope "/", PlannerWeb do
    pipe_through [:browser, :auth]
    get "/", PageController, :index
    get "/another_index", PageController, :another_index
    get "/another_other_index", PageController, :another_other_index
  end

  scope "/", PlannerWeb do
    pipe_through [:browser, :auth, :ensure_no_auth]
    get "/login", SessionController, :new
    post "/login", SessionController, :login
    get "/register", UserController, :register_page
    post "/register", UserController, :register
  end

  scope "/", PlannerWeb do
    pipe_through [:browser, :auth, :ensure_auth, :allowed_for_users]
    # Logout
    get "/logout", SessionController, :logout
    # Setting page
    get "/settings", PageController, :settings
    # Invite system of event
    post "/events/:id/invite/", EventController, :invite
    post "/events/:id/accept/", EventController, :accept_invite
    post "/events/:id/decline/", EventController, :decline_invite
    post "/events/:id/reset/", EventController, :reset_invite
    # Follow/Unfollow a user
    post "/users/:id/follow/", UserController, :follow
    post "/users/:id/unfollow/", UserController, :unfollow
    # Show all users
    get "/users", UserController, :user_index
    # Change password
    post "/change_pass", UserController, :change_pass
    put "/change_pass", UserController, :change_pass
    # Change image
    post "/change_image", UserController, :change_image
    put "/change_image", UserController, :change_image
    # Generate Api-keys
    post "/generate", ApiController, :generate
    # Still need to fix this
    resources "/events", EventController
    # Show user profile
    resources "/users", UserController, only: [:show]
  end

  scope "/admin", PlannerWeb do
    pipe_through [:browser, :auth, :ensure_auth, :allowed_for_admins]
    resources "/users", UserController
    get "/", PageController, :admin_index
  end

  scope "/api", PlannerWeb do
    pipe_through [:api]
    get "/users/:id", ApiController, :show
  end

  scope "/api", PlannerWeb do
    pipe_through [:api, :authenticate_api_user]
    get "/users", ApiController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", PlannerWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: PlannerWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

apps/planner_web/lib/planner_web/views/layout_view.ex
defmodule PlannerWeb.LayoutView do
  use PlannerWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}

  def new_locale(conn, locale, language_title) do
    "<a href=\"#{Routes.page_path(conn, :another_index, locale: locale)}\">#{language_title}</a>" |> raw
  end

end

apps/planner_web/lib/planner_web/templates/layout/app.html.heex
<main class="flex flex-grow flex-col min-h-max w-full">

  <p class="alert alert-info w-full" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger w-full" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

apps/planner_web/lib/planner_web/templates/layout/live.html.heex
<main class="flex flex-grow min-h-max flex-col w-full">
  <p class="alert alert-info w-full" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger w-full" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

apps/planner_web/lib/planner_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Planner", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
  </head>
  <body class="flex flex-col h-screen">
    <nav class="bg-gray-800" x-data="{navbarOpen:false}">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between h-16">
          <div class="flex items-center">
            <div class="flex-shrink-0">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" viewBox="0 0 20 20" fill="#3f51b5">
                <path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd" />
              </svg>
            </div>
            <div class="hidden md:block">
              <div class="ml-10 flex items-baseline space-x-4">
                <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                <a href="/" class="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium hover:bg-gray-700">Home</a>
                <%= if @current_user do %>
                  <%= link "Events", to: Routes.event_path(@conn, :index), class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
                  <%= link "Users", to: Routes.user_path(@conn, :user_index), class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>

                  <%= if @current_user.role == "Admin" do %>
                      <a href="/admin" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Admin scope</a>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="hidden md:block">
            <div class="ml-4 flex items-center md:ml-6">
  
              <%= if @current_user do %>
              <!-- Profile dropdown -->
              <div class="ml-3 relative" x-data="{dropDownOpen:false}">
                <div>
                  <button type="button" class="max-w-xs bg-gray-800 rounded-full flex items-center text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white" id="user-menu-button" aria-expanded="false" aria-haspopup="true"
                  @click="dropDownOpen = !dropDownOpen">
                    <span class="sr-only">Open user menu</span>
                    <%= img_tag(@current_user.image, class: "h-8 w-8 rounded-full object-cover") %>
                  </button>
                </div>
                <div class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1" :class="{'hidden':!dropDownOpen,'flex flex-col':dropDownOpen}" @click.away="dropDownOpen = false">
                  <%= link "Your Profile", to: Routes.user_path(@conn, :show, @current_user), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" %>
                  <a href="/settings" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Settings</a>
                  <%= link "Sign out", to: Routes.session_path(@conn, :logout), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" %>
                </div>
              </div>
              <% else %>
                <%= link "Sign In", to: Routes.session_path(@conn, :new), class: "bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium hover:bg-gray-600" %>
                <%= link "Register", to: Routes.user_path(@conn, :register_page), class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
              <% end %>
            </div>
          </div>
          <div class="-mr-2 flex md:hidden">
            <button type="button" 
            class="bg-gray-800 inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white" aria-controls="mobile-menu" aria-expanded="false"
            @click="navbarOpen = !navbarOpen"
            >
              <span class="sr-only">Open main menu</span>
              <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
              </svg>
              <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
      </div>
  
      <!-- Mobile menu, show/hide based on menu state. -->
      <div class="md:hidden":class="{'hidden':!navbarOpen,'flex flex-col':navbarOpen}" id="mobile-menu" @click.away="navbarOpen = false">
        <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
          <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
          <a href="/" class="bg-gray-900 text-white block px-3 py-2 rounded-md text-base font-medium">Home</a>

          <%= if @current_user do %>
            <%= link "Events", to: Routes.event_path(@conn, :index), class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
            <%= link "Users", to: Routes.user_path(@conn, :user_index), class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
            <%= if @current_user.role == "Admin" do %>
              <a href="/admin" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Admin scope</a>
            <% end %>
          <% else %>
            <%= link "Sign In", to: Routes.session_path(@conn, :new), class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
            <%= link "Register", to: Routes.user_path(@conn, :register_page), class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
          <% end %>
        </div>      
        <!-- User profile -->
        <%= if @current_user do %>
        <div class="pt-4 pb-3 border-t border-gray-700">
          <div class="flex items-center px-5">
            <div class="flex-shrink-0">
              <%= img_tag(@current_user.image, class: "h-10 w-10 rounded-full object-cover") %>    
            </div>
            <div class="ml-3">
              <div class="text-base font-medium leading-none text-white"><%= @current_user.username %></div>
            </div>
          </div>
          <div class="mt-3 px-2 space-y-1">
            <%= link "Your Profile", to: Routes.user_path(@conn, :show, @current_user), class: "block px-3 py-2 rounded-md text-base font-medium text-gray-400 hover:text-white hover:bg-gray-700" %>
            <a href="/settings" class="block px-3 py-2 rounded-md text-base font-medium text-gray-400 hover:text-white hover:bg-gray-700">Settings</a>
            <%= link "Sign out", to: Routes.session_path(@conn, :logout), class: "block px-3 py-2 rounded-md text-base font-medium text-gray-400 hover:text-white hover:bg-gray-700" %>
          </div>
        </div>
        <% end %>
      </div>
    </nav>

    <%= @inner_content %>
  </body>
</html>