apps/planner_web/lib/planner_web/router.ex
defmodule PlannerWeb.Router do
  use PlannerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {PlannerWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug PlannerWeb.Plugs.Locale
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug PlannerWeb.Plugs.ApiAuthorizationPlug
  end

  pipeline :auth do
    plug PlannerWeb.Pipeline
    plug PlannerWeb.CurrentUser
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :ensure_no_auth do
    plug Guardian.Plug.EnsureNotAuthenticated
  end

  pipeline :allowed_for_users do
    plug PlannerWeb.Plugs.AuthorizationPlug, ["Admin", "User"]
  end

  pipeline :allowed_for_admins do
    plug PlannerWeb.Plugs.AuthorizationPlug, ["Admin"]
  end

  scope "/", PlannerWeb do
    pipe_through [:browser, :auth]
    get "/", PageController, :index
    get "/another_index", PageController, :another_index
    get "/another_other_index", PageController, :another_other_index
  end

  scope "/", PlannerWeb do
    pipe_through [:browser, :auth, :ensure_no_auth]
    get "/login", SessionController, :new
    post "/login", SessionController, :login
    get "/register", UserController, :register_page
    post "/register", UserController, :register
  end

  scope "/", PlannerWeb do
    pipe_through [:browser, :auth, :ensure_auth, :allowed_for_users]
    # Logout
    get "/logout", SessionController, :logout
    # Setting page
    get "/settings", PageController, :settings
    # Invite system of event
    post "/events/:id/invite/", EventController, :invite
    post "/events/:id/accept/", EventController, :accept_invite
    post "/events/:id/decline/", EventController, :decline_invite
    post "/events/:id/reset/", EventController, :reset_invite
    # Follow/Unfollow a user
    post "/users/:id/follow/", UserController, :follow
    post "/users/:id/unfollow/", UserController, :unfollow
    # Show all users
    get "/users", UserController, :user_index
    # Change password
    post "/change_pass", UserController, :change_pass
    put "/change_pass", UserController, :change_pass
    # Change image
    post "/change_image", UserController, :change_image
    put "/change_image", UserController, :change_image
    # Generate Api-keys
    post "/generate", ApiController, :generate
    # Still need to fix this
    resources "/events", EventController
    # Show user profile
    resources "/users", UserController, only: [:show]
  end

  scope "/admin", PlannerWeb do
    pipe_through [:browser, :auth, :ensure_auth, :allowed_for_admins]
    resources "/users", UserController
    get "/", PageController, :admin_index
  end

  scope "/api", PlannerWeb do
    pipe_through [:api]
    get "/users/:id", ApiController, :show
  end

  scope "/api", PlannerWeb do
    pipe_through [:api, :authenticate_api_user]
    get "/users", ApiController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", PlannerWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: PlannerWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

apps/planner_web/lib/planner_web/templates/page/admin_index.html.heex
<div class="p-5">
    <a class="bg-indigo-500 text-white px-10 py-2 rounded" href={Routes.user_path(@conn, :index) } >Manage users</a>
</div>

apps/planner_web/lib/planner_web/templates/page/index.html.heex
<div class="flex justify-center items-center h-full w-full">
  <div class="typewriter">
    <h1><strong>Welcome</strong>, to the <strong>event planner</strong> you never knew you needed.</h1>
  </div>
</div>

apps/planner_web/lib/planner_web/templates/page/settings.html.heex
<div class="w-full h-full justify-center items-center flex flex-col">
  <div class="flex flex-col px-3 max-w-md w-full h-full pt-5 mb-3">
    <h1 class="text-3xl font-bold"><%= gettext "Settings" %></h1>
    <p><%= gettext "Customize your experience!" %></p>

    <div class="mt-5">
      <h3 class="text-xl font-bold"><%= gettext "Languages" %></h3>
      <p class="text-sm"><%= gettext "Choose your language" %></p>
      <ul class="flex gap-2">
        <li><%= new_locale @conn, :en, "/images/united-kingdom.png" %></li>
        <li><%= new_locale @conn, :nl, "images/netherlands.png" %></li>
      </ul>
    </div>

    <div class="mt-5">
      <h3 class="text-xl font-bold"><%= gettext "Password" %></h3>
      <p class="text-sm"><%= gettext "Change your password" %></p>
      <%= form_for @pass_changeset, Routes.user_path(@conn, :change_pass), [class: "flex flex-col w-full justify-center items-center"], fn f -> %>      
        <div class="flex flex-col w-full mt-2">
            <%= password_input f, :password, class: "bg-white h-10 rounded outline-none px-4 text-md border border-black bg-transparent", placeholder: gettext "Password" %>
            <%= error_tag f, :password %>
        </div>       
        <div class="flex flex-col w-full mt-5">
            <%= submit "Submit" , class: "btn btn-primary w-full bg-blue-700 h-10 rounded text-white font-medium text-md" %>
        </div>
      <% end %>
    </div>

    <div class="mt-5">
      <h3 class="text-xl font-bold"><%= gettext "Profile image" %></h3>
      <p class="text-sm"><%= gettext "Change your profile image" %></p>
      <%= form_for @image_changeset, Routes.user_path(@conn, :change_image), [class: "flex flex-col w-full justify-center items-center"], fn f -> %>      
        <div class="flex flex-col w-full mt-2">
            <%= text_input f, :image, class: "bg-white h-10 rounded outline-none px-4 text-md border border-black bg-transparent", placeholder: gettext "Image link" %>
            <%= error_tag f, :image %>
        </div>       
        <div class="flex flex-col w-full mt-5">
            <%= submit "Submit" , class: "btn btn-primary w-full bg-blue-700 h-10 rounded text-white font-medium text-md" %>
        </div>
      <% end %>
    </div>

    <div class="mt-5">
      <h3 class="text-xl font-bold">Api</h3>
      <p class="text-sm"><%= gettext "Generate an api-key" %></p>
      <div class="flex flex-col w-full mt-5 mb-2">
        <%= link "Generate", to: Routes.api_path(@conn, :generate), method: :post, class: "btn btn-primary w-full bg-blue-700 h-10 rounded text-white font-medium text-md flex justify-center items-center" %>
      </div>
      <%= for key <- @keys do %>
        <p><%= key.key %></p>
      <% end %>
    </div>
    
  </div>
</div>